/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin/route'
import { Route as IndexImport } from './routes/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as AdminSubcategoriesIndexImport } from './routes/admin/subcategories/index'
import { Route as AdminIngredientsIndexImport } from './routes/admin/ingredients/index'
import { Route as AdminFoodsIndexImport } from './routes/admin/foods/index'
import { Route as AdminCategoriesIndexImport } from './routes/admin/categories/index'

// Create/Update Routes

const AdminRouteRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const AdminSubcategoriesIndexRoute = AdminSubcategoriesIndexImport.update({
  id: '/subcategories/',
  path: '/subcategories/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminIngredientsIndexRoute = AdminIngredientsIndexImport.update({
  id: '/ingredients/',
  path: '/ingredients/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminFoodsIndexRoute = AdminFoodsIndexImport.update({
  id: '/foods/',
  path: '/foods/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminCategoriesIndexRoute = AdminCategoriesIndexImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/foods/': {
      id: '/admin/foods/'
      path: '/foods'
      fullPath: '/admin/foods'
      preLoaderRoute: typeof AdminFoodsIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/ingredients/': {
      id: '/admin/ingredients/'
      path: '/ingredients'
      fullPath: '/admin/ingredients'
      preLoaderRoute: typeof AdminIngredientsIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/subcategories/': {
      id: '/admin/subcategories/'
      path: '/subcategories'
      fullPath: '/admin/subcategories'
      preLoaderRoute: typeof AdminSubcategoriesIndexImport
      parentRoute: typeof AdminRouteImport
    }
  }
}

// Create and export the route tree

interface AdminRouteRouteChildren {
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminFoodsIndexRoute: typeof AdminFoodsIndexRoute
  AdminIngredientsIndexRoute: typeof AdminIngredientsIndexRoute
  AdminSubcategoriesIndexRoute: typeof AdminSubcategoriesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminFoodsIndexRoute: AdminFoodsIndexRoute,
  AdminIngredientsIndexRoute: AdminIngredientsIndexRoute,
  AdminSubcategoriesIndexRoute: AdminSubcategoriesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/foods': typeof AdminFoodsIndexRoute
  '/admin/ingredients': typeof AdminIngredientsIndexRoute
  '/admin/subcategories': typeof AdminSubcategoriesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/foods': typeof AdminFoodsIndexRoute
  '/admin/ingredients': typeof AdminIngredientsIndexRoute
  '/admin/subcategories': typeof AdminSubcategoriesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/foods/': typeof AdminFoodsIndexRoute
  '/admin/ingredients/': typeof AdminIngredientsIndexRoute
  '/admin/subcategories/': typeof AdminSubcategoriesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/categories'
    | '/admin/foods'
    | '/admin/ingredients'
    | '/admin/subcategories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/categories'
    | '/admin/foods'
    | '/admin/ingredients'
    | '/admin/subcategories'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login/'
    | '/admin/categories/'
    | '/admin/foods/'
    | '/admin/ingredients/'
    | '/admin/subcategories/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/login/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin/route.tsx",
      "children": [
        "/admin/categories/",
        "/admin/foods/",
        "/admin/ingredients/",
        "/admin/subcategories/"
      ]
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/admin/categories/": {
      "filePath": "admin/categories/index.tsx",
      "parent": "/admin"
    },
    "/admin/foods/": {
      "filePath": "admin/foods/index.tsx",
      "parent": "/admin"
    },
    "/admin/ingredients/": {
      "filePath": "admin/ingredients/index.tsx",
      "parent": "/admin"
    },
    "/admin/subcategories/": {
      "filePath": "admin/subcategories/index.tsx",
      "parent": "/admin"
    }
  }
}
ROUTE_MANIFEST_END */
